// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTable = "table"

// Table mapped from table <table>
type Table struct {
	ID          string         `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(6);not null;index:created_at,priority:1;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(6);not null;index:updated_at,priority:1;default:current_timestamp(6) on update current_timestamp(6)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(6);index:deleted_at,priority:1" json:"deleted_at"`
	Title       *string        `gorm:"column:title;type:longtext" json:"title"`
	Status      string         `gorm:"column:status;type:varchar(31);not null" json:"status"`
	Author      string         `gorm:"column:author;type:varchar(255);not null" json:"author"`
	DisplayTime time.Time      `gorm:"column:display_time;type:datetime(6);not null;index:created_at,priority:2;default:CURRENT_TIMESTAMP(6)" json:"display_time"`
	PageViews   int64          `gorm:"column:page_views;type:bigint(20);not null" json:"page_views"`
}

// TableName Table's table name
func (*Table) TableName() string {
	return TableNameTable
}
